version: '3.8'

services:
  backend:
    container_name: prematch_backend
    build: ./backend
    ports:
      - "8888:8888"
    depends_on:
      - redis

  frontend:
    container_name: prematch_frontend
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  redis:
    container_name: prematch_redis
    image: redis:latest
    ports:
      - "6379:6379"
