version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8888:8888"
    volumes:
      - ./backend:/app
    depends_on:
      - redis

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
